### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [angelaturi/gogh-and-co#2]
- [x] Signin appears to just want an email and a password, signup wants a first name and a last name as well. Please account for this on your users table 
- [x] You will want an Artists table, where the artworks table holds a foreign key referencing the artist or creator 
- [x] What are the color options for the color column on the artworks table (specify). Same with style, type, and medium column. 
- [x] What is the Museum column on the Artworks table?
- [x] What are Galleries? I cannot find that functionality on Arts&Culture. 

Let me know if you have any questions!

**Comment by angelaturi** [comment]
The Museum column on the Artworks table is the "partner organization" that owns the artwork (i.e. The Museum of Modern Art).

Users can group/curate favorited artworks into 'personalized virtual exhibitions' via Galleries. Galleries have a title, description, and include any number of artworks.
